# -*- coding: utf-8 -*-
"""DL Project 1. Breast Cancer Classification with NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kB-kvuJIsL5k4ECP_83PJ0jqeiOBMv-l
"""

import sklearn.datasets
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

dataset = sklearn.datasets.load_breast_cancer()
dataset

X = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)

X.tail()

lst = [dataset.target_names[1]]
Y = pd.DataFrame(data=dataset.target, columns=lst)

Y.head()

Y.value_counts()

df = X

df['benign'] = Y

df.tail()

df.shape

# To check How many Null values are present in dataset
df.info()

df.describe()

df['benign'].value_counts()

hm = sns.heatmap(df.corr())

X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

X.head()

Y.head()

# using the train test split function
X_train, X_test, y_train, y_test = train_test_split(X,y ,
                                   random_state=104,
                                   test_size=0.25,
                                   shuffle=True)

from sklearn.preprocessing import StandardScaler

obj = StandardScaler()

X_train_std = obj.fit_transform(X_train)
X_test_std = obj.fit_transform(X_test)

import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Flatten(input_shape = (30,)),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(2, activation='sigmoid'),
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train_std, y_train, epochs=10, validation_split=0.1)

loss, accuracy = model.evaluate(X_test_std, y_test)
print(accuracy)

y_pred = model.predict(X_test_std)

y_pred

y_pred.shape

import numpy as np

y_pred_labels = [np.argmax(i) for i in y_pred]
print(y_pred_labels)

